id: P00BB9AB4
initial_creation_type: input
source_metadata:
  title: Minling Terchen Gyurme Dorje Series
  language: fr
  description: 'Texts by the famous treasure-revealer Gyurme Dorje (''gyur med rdo
    rje, 1646–1714) alias Terdak Lingpa (gter bdag gling pa), the founder of Mindroling
    Monastery:'
  volume:
    84d6e9dced174926b1b0535186c24175:
      title: The Secret Vajra Knot
      parent: Aspiration Prayers
    5239800062ec4ddebde8891c9a2816b1:
      title: 'Liberation Upon Hearing: An Explanation of the Phenomena of the Intermediate
        State'
      parent: Bardo
    a2b3c78a15d0412fbd376de16d447c0b:
      title: 'Damchen Chitor: A Brief Practice of Torma Offering to the Oath-Bound
        Guardians'
      parent: Dharma Protectors
    e3db5a3b1b8a4bdf965d31f7f123d8c4:
      title: General Long-Life Prayer
      parent: Longevity
    0704f302f1ce4fd6ad249e9f30c5b2d8:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Sādhanas
    f24f174c74684e2a9c4a6e08e99b6bb5:
      title: 'Final Words: The Essential Advice'
      parent: Testament
created_at: '2022-03-01T00:48:16.497682'
last_modified_at: '2022-03-01T00:48:16.497688'
